# Generated by Django 5.2.3 on 2025-08-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=100)),
                ('nomeSocial', models.CharField(max_length=100)),
                ('dataNascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('orgaoEmissor', models.CharField(max_length=100)),
                ('dataEmissao', models.DateField()),
                ('estadoCivil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo'), ('U', 'União Estável')], max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nomeMae', models.CharField(max_length=100)),
            ],
        ),
    ]
