# Generated by Django 5.2.3 on 2025-08-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario2',
            options={'verbose_name': 'Formulário', 'verbose_name_plural': 'Formulários'},
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='dataEmissao',
            field=models.DateField(verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='dataNascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='estadoCivil',
            field=models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo'), ('U', 'União Estável')], max_length=1, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='nomeCompleto',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='nomeMae',
            field=models.CharField(max_length=100, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='nomeSocial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Social'),
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='orgaoEmissor',
            field=models.CharField(max_length=10, verbose_name='Órgão Emissor'),
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='rg',
            field=models.CharField(max_length=20, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='formulario2',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
