# Generated by Django 5.2.3 on 2025-08-01 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario2', '0002_alter_formulario2_options_alter_formulario2_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('log_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('automation_data', models.JSONField(blank=True, default=dict)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='formulario2.formulario2')),
            ],
            options={
                'verbose_name': 'Log de Automação',
                'verbose_name_plural': 'Logs de Automação',
                'ordering': ['-started_at'],
            },
        ),
    ]
