# Generated by Django 5.2.3 on 2025-08-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario2', '0003_automationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioAmil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome*')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF*')),
                ('nome_cartao', models.CharField(max_length=100, verbose_name='Nome no cartão*')),
                ('data_inclusao', models.DateField(verbose_name='Data de inclusão*')),
                ('data_registro', models.DateField(verbose_name='Data de registro*')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento*')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo*')),
                ('nacionalidade', models.CharField(choices=[('B', 'Brasileiro'), ('E', 'Estrangeiro')], default='B', max_length=1, verbose_name='Nacionalidade')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Nome da mãe*')),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do pai')),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo'), ('U', 'União Estável')], max_length=1, verbose_name='Estado civil*')),
                ('plano', models.CharField(max_length=100, verbose_name='Plano*')),
                ('contrato_dental', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contrato Dental')),
                ('plano_dental', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plano Dental')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formulário Amil',
                'verbose_name_plural': 'Formulários Amil',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='formulario2',
            options={'verbose_name': 'Formulário Porto', 'verbose_name_plural': 'Formulários Porto'},
        ),
    ]
