# Generated by Django 5.2.3 on 2025-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario2', '0004_formularioamil_alter_formulario2_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioamil',
            name='nacionalidade',
            field=models.CharField(blank=True, choices=[('B', 'Brasileiro'), ('E', 'Estrangeiro')], default='B', max_length=1, null=True, verbose_name='Nacionalidade'),
        ),
    ]
